<?php

namespace AppBundle\Repository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Recovering all Genres
     */
    public function getAllGenres(): array
    {
        // Création de la requete (qui devient un objet) qui va select * from genre et on la stocke pour utilisation
        $qb = $this->createQueryBuilder('g')
            // On affiche par odre alphabétique
            ->orderBy('g.name', 'ASC')
            ->getQuery();

        // On demande à l'objet d'executer la requete, on renvoie donc tous les genres
        return $qb->execute();
    }

}
