<?php

namespace AppBundle\Repository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllLocations(): array
    {
        // Création de la requete (qui devient un objet) qui va select * from genre et on la stocke pour utilisation
        $qb = $this->createQueryBuilder('l')
            // On affiche par odre alphabétique
            ->orderBy('l.address', 'ASC')
            ->getQuery();

        // On demande à l'objet d'executer la requete, on renvoie donc toutes les localisations
        return $qb->execute();
    }
}
